export const SHOW_EDIT_TITLE = 'CARD_DETAIL/CHECKLISTS/SHOW_EDIT_TITLE'
export const HIDE_EDIT_TITLE = 'CARD_DETAIL/CHECKLISTS/HIDE_EDIT_TITLE'
export const SHOW_ADD_CHECKLIST_ITEM = 'CARD_DETAIL/CHECKLISTS/SHOW_ADD_CHECKLIST_ITEM'
export const HIDE_ADD_CHECKLIST_ITEM = 'CARD_DETAIL/CHECKLISTS/HIDE_ADD_CHECKLIST_ITEM'
