export const MOVE_LIST = 'LIST/MOVE_LIST'
export const UPDATE_LIST_REQUEST = 'LIST/UPDATE_LIST_REQUEST'
export const UPDATE_LIST_SUCCESS = 'LIST/UPDATE_LIST_SUCCESS'
export const UPDATE_LIST_ERROR = 'LIST/UPDATE_LIST_ERROR'
