export const BOARDS_REQUEST = 'BOARDS/BOARDS_REQUEST'
export const BOARDS_SUCCESS = 'BOARDS/BOARDS_SUCCESS'
export const BOARDS_ERROR = 'BOARDS/BOARDS_ERROR'

export const CREATE_BOARD_REQUEST = 'BOARDS/CREATE_BOARD_REQUEST'
export const CREATE_BOARD_SUCCESS = 'BOARDS/CREATE_BOARD_SUCCESS'
export const CREATE_BOARD_ERROR = 'BOARDS/CREATE_BOARD_ERROR'
